### ISSUE TITLE
Exception when deleting a Job

### ISSUE THREAD

**Issue by dangrystad** [FlavioF/quartz-scheduler-hazelcast-jobstore#44]
# Problem
Sometimes when a Job is deleted via StdScheduler.deleteJob(...) the following exception is produced.
```
11:15:39.431 ERROR[org.quartz.core.QuartzSchedulerThread   ][||] quartzSchedulerThreadLoop: RuntimeException null (run:287)
java.lang.NullPointerException: null
	at com.bikeemotion.quartz.jobstore.hazelcast.HazelcastJobStore.acquireNextTriggers(HazelcastJobStore.java:883) ~[quartz-hazelcast-jobstore-1.0.2.jar:1.0.2]
	at org.quartz.core.QuartzSchedulerThread.run(QuartzSchedulerThread.java:272) ~[quartz-2.2.3.jar:na]
11:15:39.431 DEBUG[c.b.q.j.hazelcast.HazelcastJobStore     ][||] Misfire applied TriggerWrapper{trigger=Trigger 'DEFAULT.6da64b5bd2ee-861c35f6-e77d-4704-98e8-374d79bcfd71':  triggerClass: 'org.quartz.impl.triggers.SimpleTriggerImpl calendar: 'null' misfireInstruction: 0 nextFireTime: Thu Nov 24 11:15:39 CET 2016, state=WAITING, nextFireTime=1479982539431, acquiredAt=null} (acquireNextTriggers:864)
11:15:39.432 DEBUG[c.b.q.j.hazelcast.HazelcastJobStore     ][||] Misfire applied TriggerWrapper{trigger=Trigger 'DEFAULT.6da64b5bd2ee-861c35f6-e77d-4704-98e8-374d79bcfd71':  triggerClass: 'org.quartz.impl.triggers.SimpleTriggerImpl calendar: 'null' misfireInstruction: 0 nextFireTime: Thu Nov 24 11:15:39 CET 2016, state=WAITING, nextFireTime=1479982539432, acquiredAt=null} (acquireNextTriggers:864)
11:15:39.433 DEBUG[c.b.q.j.hazelcast.HazelcastJobStore     ][||] Misfire applied TriggerWrapper{trigger=Trigger 'DEFAULT.6da64b5bd2ee-861c35f6-e77d-4704-98e8-374d79bcfd71':  triggerClass: 'org.quartz.impl.triggers.SimpleTriggerImpl calendar: 'null' misfireInstruction: 0 nextFireTime: Thu Nov 24 11:15:39 CET 2016, state=WAITING, nextFireTime=1479982539433, acquiredAt=null} (acquireNextTriggers:864)
11:15:39.435 DEBUG[c.b.q.j.hazelcast.HazelcastJobStore     ][||] Misfire applied TriggerWrapper{trigger=Trigger 'DEFAULT.6da64b5bd2ee-861c35f6-e77d-4704-98e8-374d79bcfd71':  triggerClass: 'org.quartz.impl.triggers.SimpleTriggerImpl calendar: 'null' misfireInstruction: 0 nextFireTime: Thu Nov 24 11:15:39 CET 2016, state=WAITING, nextFireTime=1479982539435, acquiredAt=null} (acquireNextTriggers:864)
```
I believe that it is a concurrency problem where the job is deleted while HazelcastJobStore.acquireNextTriggers is running. If I change the code to this problem goes away.
```
        final JobKey jobKey = tw.trigger.getJobKey();
        final JobDetail job = jobsByKey.get(tw.trigger.getJobKey());

        // If trigger's job is set as @DisallowConcurrentExecution, and it has
        // already been added to result, then
        // put it back into the timeTriggers set and continue to search for next
        // trigger.
        if (job == null) {
          LOG.debug("Job not found);
          continue;
        } else if(job.isConcurrentExectionDisallowed()) {
          if (acquiredJobKeysForNoConcurrentExec.contains(jobKey)) {
            continue; // go to next trigger in queue.
          } else {
            acquiredJobKeysForNoConcurrentExec.add(jobKey);
          }
        }
```
The question is if this is safe?

**Comment by FlavioF** [comment]
It looks good!

Thank you.

**Comment by dangrystad** [comment]
Thanks!
